config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'journals#index'
  root 'static_pages#show', page: 'home'
  get '/faq' => 'pages#faq'
  get '/journals/:journal_id/docs/:doc_id/items/:id' => 'journal_docs#lend', as: :lend_doc_item

  namespace :admin do
    root 'application#index'

    resources :journals, only: %i[index new edit update create destroy] do
      resources :docs, only: %i[new edit update create destroy],
                       controller: 'journal_docs' do
        resources :tags, only: [] do
          member do
            delete :remove
          end
        end
      end

      member do
        post :reorder
      end
    end

    resources :books
    resources :orders do
      member do
        post :cancel
        post :prepare
        post :lend
        post :return
      end
    end

    resources :magazines

    resources :csv_imports
    resources :csv_exports

    resources :docs, only: %i[index new edit update create destroy] do
      collection do
        post :bulk_update
        post :import
      end
    end

    resources :versions do
      post :undo
    end

    resources :users do
      member do
        patch :archive
      end
    end

    resources :states, only: %i[index new create] do
      member do
        get :make_default
      end
    end

    resources :departments
  end
  # --- end of admin routes

  resources :journals, only: %i[index show] do
    resources :docs, controller: 'journal_docs' do
      resources :comments, only: [:create]

      resources :tags, only: [] do
        member do
          delete :remove
        end
      end
    end
  end

  resources :docs, only: %i[index show] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  # resources :books, only: %i[index show]
  resources :books do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :orders

  resources :cart_items

  resources :magazines, only: %i[index show]

  resources :attachments, only: %i[show new]

  namespace :account do
    resources :orders
  end
end

app/models/order.rb
class Order < ApplicationRecord
  include AASM

  aasm do
    state :borrow_required, initial: true
    state :prepared
    state :lended
    state :order_cancelled
    state :book_returned

    event :prepare do
      transitions from: :borrow_required, to: :prepared
    end

    event :lend do
      transitions from: :prepared, to: :lended
    end

    event :return_book do
      transitions from: :lended, to: :book_returned
    end

    event :cancel_order do
      transitions from: %i[order_placed prepared], to: :order_cancelled
    end
  end

  before_create :generate_token
  belongs_to :user

  validates :borrower, presence: true
  validates :borrow_at, presence: true

  has_many :borrow_lists

  def generate_token
    self.token = SecureRandom.uuid
  end
end

app/controllers/account/orders_controller.rb
class Account::OrdersController < ApplicationController
  before_action :authenticate_user!
  skip_after_action :verify_authorized, :verify_policy_scoped

  def index
    @orders = current_user.orders.order('id DESC')
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  layout 'admin'
  skip_after_action :verify_authorized, :verify_policy_scoped
  before_action :authenticate_user!
  before_action :admin_required
  before_action :set_order, only: %i[show prepare cancel lend return]

  def index
    @orders = Order.order('id DESC')
  end

  def show
    @borrow_lists = @order.borrow_lists
  end

  def prepare
    @order.prepare!
    redirect_back fallback_location: admin_order_path
  end

  def cancel
    @order.cancel_order!
    redirect_back fallback_location: admin_order_path
  end

  def lend
    @order.lend!
    redirect_back fallback_location: admin_order_path
  end

  def return
    @order.return_book!
    redirect_back fallback_location: admin_order_path
  end

  private

  def set_order
    @order = Order.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = ''
    redirect_to admin_orders_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  skip_after_action :verify_authorized, :verify_policy_scoped

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.aasm_state = 'borrow_required'
    # @order.total = cart_items.total
    if @order.save
      current_cart.cart_items.each do |cart_item|
        borrow_list = BorrowList.new
        borrow_list.order = @order
        borrow_list.book = cart_item.book
        borrow_list.quantity = cart_item.quantity
        borrow_list.save
      end
      current_cart.clean!
      redirect_to order_path(@order.token)
    else
      render 'carts/checkout'
    end
  end

  def show
    @order = Order.find_by_token(params[:id])
    @borrow_lists = @order.borrow_lists
  end

  private

  def order_params
    params.require(:order).permit(:borrower, :borrow_at, :due_at)
  end
end

app/helpers/account/orders_helper.rb
module Account::OrdersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_state_option.html.erb
<div style="padding: 10px; float: right;">
  <% case order.aasm_state %>
    <% when "borrow_required" %>
      <%= link_to("取消订单", cancel_admin_order_path(order), method: :post, class: "btn btn-default btn-sm") %>
      <%= link_to("准备图书", prepare_admin_order_path(order), method: :post, class: "btn btn-default btn-sm") %>
      <% when "prepared" %>
        <%= link_to("取消订单", cancel_admin_order_path(order), method: :post, class: "btn btn-default btn-sm") %>
        <%= link_to("借出", lend_admin_order_path(order), method: :post, class: "btn btn-default btn-sm") %>
        <% when "lended" %>
          <%= link_to("归还", return_admin_order_path(order), method: :post, class: "btn btn-default btn-sm") %>
          <% when "order_cancelled" %>
            <span class="label label-default">借阅已取消</span>
            <% when "book_returned" %>
              <span class="label label-default">图书已归还</span>
            <% end %>
          </div>

app/views/admin/orders/index.html.erb
<h2>借阅清单</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>生成时间</th>
      <th>借阅人员</th>
      <th>借阅状态</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to(order.id, admin_order_path(order)) %></td>
        <td><%= order.created_at.to_s(:long) %></td>
        <td><%= order.user.cname %></td>
        <td><%= order.aasm_state %></td>
      </tr>
    <% end %>

  </tbody>
</table>

app/views/admin/orders/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>借阅明细</h2>
    <%= render "admin/orders/state_option", order: @order %>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">图书明细</th>
          <th>数量</th>
        </tr>
      </thead>
      <tbody>
        <% @order.borrow_lists.each do |borrow_list| %>
          <tr>
            <td><%= borrow_list.book.title %></td>
            <td><%= borrow_list.quantity %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">总计
        <%= @order.total %>
        本</span>
    </div>

    <h2>借阅情况</h2>
    <table class="table table-striped table-bordered">
      <tbody>
        <tr>
          <td>借阅人</td>

          <td><%= @order.borrower %></td>
        </tr>
        <tr>
          <td>借阅时间</td>

          <td><%= @order.borrow_at %></td>
        </tr>
        <tr>
          <td>归还时间</td>

          <td><%= @order.due_at %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>