config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'journals#index'
  root 'static_pages#show', page: 'home'
  get '/faq' => 'pages#faq'
  get '/journals/:journal_id/docs/:doc_id/items/:id' => 'journal_docs#lend', as: :lend_doc_item

  namespace :admin do
    root 'application#index'

    resources :journals, only: %i[index new edit update create destroy] do
      resources :docs, only: %i[new edit update create destroy],
                       controller: 'journal_docs' do
        resources :tags, only: [] do
          member do
            delete :remove
          end
        end
      end

      member do
        post :reorder
      end
    end

    resources :books
    resources :orders do
      member do
        post :cancel
        post :prepare
        post :lend
        post :return
      end
    end

    resources :magazines

    resources :csv_imports
    resources :csv_exports

    resources :docs, only: %i[index new edit update create destroy] do
      collection do
        post :bulk_update
        post :import
      end
    end

    resources :versions do
      post :undo
    end

    resources :users do
      member do
        patch :archive
      end
    end

    resources :states, only: %i[index new create] do
      member do
        get :make_default
      end
    end

    resources :departments
  end
  # --- end of admin routes

  resources :journals, only: %i[index show] do
    resources :docs, controller: 'journal_docs' do
      resources :comments, only: [:create]

      resources :tags, only: [] do
        member do
          delete :remove
        end
      end
    end
  end

  resources :docs, only: %i[index show] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  # resources :books, only: %i[index show]
  resources :books do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :orders

  resources :cart_items

  resources :magazines, only: %i[index show]

  resources :attachments, only: %i[show new]

  namespace :account do
    resources :orders
  end
end

app/controllers/admin/journal_docs_controller.rb
class Admin::JournalDocsController < ApplicationController
  layout 'admin'

  skip_after_action :verify_authorized, :verify_policy_scoped

  before_action :find_journal
  before_action :find_doc, only: %i[show edit update destroy]

  def index
    @docs = @journal.docs.order('id DESC').page(params[:page]).per(10)

    if params[:status].present? && Doc::STATUS.include?(params[:status])
      @docs = @docs.by_status(params[:status])
    end
  end

  def show
    @comment = @doc.comments.build
  end

  def edit; end

  ## TODO: if doc.apartments updates, doc.amount need update
  def update
    if @doc.update(doc_params)
      flash[:notice] = '更新资料成功'
      redirect_to journal_doc_path(@journal, @doc)
    else
      flash[:alert] = '更新资料未成功'
      render :edit
    end
  end

  def destroy
    @doc.destroy
    flash[:notice] = '资料删除成功'
    redirect_to admin_journal_docs_path
  end

  def new
    @doc = @journal.docs.build
    @doc.departments = @journal.departments
    @doc.amount = @journal.amount
    @doc.attachments.build
  end

  def create
    @doc = @journal.docs.new

    whitelisted_params = doc_params
    # whitelisted_params.delete(:tag_names)

    @doc.attributes = whitelisted_params
    @doc.editor = current_user
    @doc.items = []

    @doc.attachments.each do |att|
      att.doc = @doc
    end

    if @doc.save
      if @doc.departments.any? { |dept| dept.name == '资料处' }
        item = Item.new
        item.owner = '资料处'
        item.doc_id = @doc.id
        item.name = @doc.id.to_s + '-1'
        @doc.items.append(item)
      end
      @doc.save
      flash[:notice] = '新增资料成功'
      redirect_to journal_doc_path(@journal, @doc)
    else
      flash[:alert] = '新增资料未成功资料'
      render :new
    end
  end

  def bulk_update
    total = 0
    if params[:commit] == I18n.t(:bulk_update)
      Array(params[:ids]).each do |doc_id|
        # TODO: @journal
        doc = Doc.find(doc_id)
        doc.status = params[:doc_status]
        total += 1 if doc.save
      end
      flash[:notice] = I18n.t(:bulk_update) + " #{total} 篇"
    elsif params[:commit] == I18n.t(:bulk_delete)
      Array(params[:ids]).each do |doc_id|
        doc = Doc.find(doc_id)
        doc.destroy
        total += 1
      end
      flash[:alert] = I18n.t(:bulk_delete) + " #{total} 篇"
    end
  end

  private

  def find_doc
    @doc = Doc.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = '您所查看的外来资料不存在'
    redirect_to admin_journals_path
  end

  def find_journal
    @journal = Journal.find_by_shortname!(params[:journal_id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = '您所查看的外来资料不存在'
    redirect_to admin_journals_path
  end

  def doc_params
    params.require(:doc)
          .permit(:origin, :name, :receive, :publish, :journal_id, :level,
                  :description, :editor, :amount, :tag_names, :status,
                  :remove_images,
                  items: [],
                  images: [],
                  department_ids: [],
                  attachments_attributes: %i[id file file_cache
                                             description _destory])
  end
end

app/controllers/journal_docs_controller.rb
class JournalDocsController < ApplicationController
  skip_after_action :verify_authorized, :verify_policy_scoped

  before_action :find_journal
  before_action :find_doc, only: %i[show edit update destroy lend]

  def index
    @docs = @journal.docs.order('id DESC').page(params[:page]).per(10)

    if params[:status].present? && Doc::STATUS.include?(params[:status])
      @docs = @docs.by_status(params[:status])
    end
  end

  def show
    @comment = @doc.comments.build
  end

  def edit; end

  def update
    if @doc.update(doc_params)
      flash[:notice] = '更新资料成功'
      redirect_to journal_doc_path(@journal, @doc)
    else
      flash[:alert] = '更新资料未成功'
      render :edit
    end
  end

  def destroy
    @doc.destroy
    flash[:notice] = '资料删除成功'
    redirect_to journal_docs_path(@journal)
  end

  def new
    @doc = @journal.docs.build
    @doc.departments = @journal.departments
    @doc.attachments.build
  end

  def create
    @doc = @journal.docs.build(doc_params)

    # whitelisted_params = doc_params
    # whitelisted_params.delete(:tag_names)
    #
    # @doc.attributes = whitelisted_params
    @doc.editor = current_user

    @doc.attachments.each do |att|
      att.doc = @doc
    end

    if @doc.save
      flash[:notice] = '新增资料成功'
      redirect_to journal_doc_path(@journal, @doc)
    else
      flash[:alert] = '新增资料未成功999'
      render :new
    end
  end

  def bulk_update
    total = 0
    if params[:commit] == I18n.t(:bulk_update)
      Array(params[:ids]).each do |doc_id|
        # TODO: @journal
        doc = Doc.find(doc_id)
        doc.status = params[:doc_status]
        total += 1 if doc.save
      end
      flash[:notice] = I18n.t(:bulk_update) + " #{total} 篇"
    elsif params[:commit] == I18n.t(:bulk_delete)
      Array(params[:ids]).each do |doc_id|
        doc = Doc.find(doc_id)
        doc.destroy
        total += 1
      end
      flash[:alert] = I18n.t(:bulk_delete) + " #{total} 篇"
    end
  end

  def lend
    redirect_to journal_doc_path(@journal, @doc)
  end

  private

  def find_doc
    id = params[:id] || params[:doc_id]
    @doc = Doc.find(id)
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = '您所查看的外来资料不存在'
    redirect_to admin_journals_path
  end

  def find_journal
    @journal = Journal.find_by_shortname!(params[:journal_id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = '您所查看的外来资料不存在'
    redirect_to admin_journals_path
  end

  def doc_params
    params.require(:doc)
          .permit(:origin, :name, :receive, :publish, :journal_id, :level,
                  :description, :editor, :amount, :tag_names, :status,
                  attachments_attributes: %i[file file_cache],
                  department_ids: [])
  end
end

app/helpers/admin/journal_docs_helper.rb
module Admin::JournalDocsHelper
end

app/helpers/journal_docs_helper.rb
module JournalDocsHelper
end

app/views/journal_docs/_form.html.erb
<%= f.association :journal, label: '刊物名称' %>
<%= f.input :name, label: "资料标题" %>
<%= f.input :origin, label: "原始编号" %>
<%= f.input :level, label: "私密程度", as: :select, prompt: "请选择私密程度",
  collection: Doc::LEVEL.map { |s| [t(s, :scope=>"doc_.level"), s] } %>
<%= f.input :status, label: "资料状态", as: :radio_buttons,
  collection: Doc::STATUS.map { |s| [t(s, :scope=>"doc_.status"), s] },
  class: "btn-group" %>
<%= f.input :receive, as: :string, label: "到刊时间",
  input_html: { data: { behaviour: "datepicker" }}  %>
<%= f.input :publish, as: :string, label: "出版时间",
  input_html: { data: { behaviour: "datepicker" }}  %>
<%= f.input :description, as: :text, label: "资料描述" %>
<%= render "tags/form", f: f %>
<%= f.input :amount, label: "资料份数" %>
<%= f.association :departments, as: :check_boxes, label: "资料分发" %>
<div id="attachments">
  <%= render partial: "attachments/form", locals: { f: f, index: 0 } %>
</div>
<p>
  <%= link_to "新增附件", new_attachment_path, remote: true, id: "add_file",
    data: { params: { index: @doc.attachments.size } } %>
</p>
<script>
  $("#doc_journal_id").select2( {theme: "bootstrap"} );
  $("#doc_receive").datepicker({ format: "yyyy-mm-dd",
    language: "<%= I18n.locale %>" });
  $("#doc_publish").datepicker({ format: "yyyy-mm-dd",
    language: "<%= I18n.locale %>" });
</script>

app/views/journal_docs/edit.html.erb
<header>
  <h3>迁移至 new_admin_journal_doc_path</h3>
</header>
<% if false %>
<%= simple_form_for [@journal, @doc] do |f| %>
  <%= render partial: "form", locals: { f: f } %>
  <%= f.submit t("update") + t("blank") + t("doc"),
    data: { disable_with: "资料更新中……" },
    class: "btn btn-primary" %>
<% end %>
<% end %>

app/views/journal_docs/index.html.erb
<header>
  <h3><%= t("doc_list") %></h3>
<% admins_only do %>
<ul class="actions" style="padding-bottom: 5px;">
  <li>
    <%= link_to(t("create") + t("blank") + t("doc"),
      new_admin_journal_doc_path, class: "new") %>
  </li>
</ul>
<% end %>
</header>
<div class="submenu">
  <div class="btn-group">
    <%= link_to "#{t('all')} (#{@journal.docs.count})",
      journal_docs_path(status: nil),
      class: "btn btn-success btn-group
              #{(params[:status].blank?) ? "active" : "" }" %>
    <% Doc::STATUS.each do |s| %>
      <%= link_to t(s, scope: 'doc_.status') + " (#{@journal.docs.by_status(s).count})",
        journal_docs_path(status: s),
        class: "btn btn-success btn-group
                #{(params[:status].blank?) ? "active" : "" }" %>
    <% end %>
  </div>
</div>
<div id="docs" class="row">
  <%= form_tag bulk_update_admin_docs_path, class: "table" do %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>
          <%= check_box_tag "全选", "1", false, id: "toggle_all" %>
        </th>
        <th>
          <%= t("num") %>
        </th>
        <th>
          <%= t("journal") + t("blank") + t("name") %>
        </th>
        <th>
          <%= t("doc") + t("blank") + t("name") %>
        </th>
        <th>
          <%= t("origin") %>
        </th>
        <!-- <th>
          <%= t("receivecount") %>
        </th> -->
        <th>
          <%= t("receive") %>
        </th>
        <th>
          <%= t("operation") %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @docs.each do |doc| %>
      <tr>
        <td>
          <%= check_box_tag "ids[]", doc.id %>
        </td>
        <td>
          <%= doc.id %>
        </td>
        <td>
          <%= doc.journal.name %>
        </td>
        <td>
          <%= link_to doc.name, journal_doc_path(doc.journal, doc)  %>
        </td>
        <td>
          <%= doc.origin %>
        </td>
        <!-- <td>
          <%= doc.amount %>
        </td> -->
        <td>
          <%= doc.receive %>
        </td>
        <td>
          <%= link_to t("edit"), edit_admin_journal_doc_path(@journal, doc), class: "edit" %>
          <%= link_to t("delete"), journal_doc_path(@journal, doc),
              method: :delete, data: { confirm: "确定要删除这份资料么？" },
              class: "delete"%>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @docs %>

<p>
<%= select_tag :doc_status,
  options_for_select([[t("available", scope: "doc_.status"), "available"],
                      [t("lend", scope: "doc_.status"), "lend"]]),
  class: "form-control", style: "width: 80px; display: inline"%>
<%= submit_tag t(:bulk_update), class: "btn btn-primary" %>
<%= submit_tag t(:bulk_delete), class: "btn btn-danger",
  data: { confirm: "你确定要批量删除么？" } %>
</p>
<% end %>
</div>
<script>
$("#toggle_all").click(function(){
  if ( $(this).prop("checked") ) {
    $("input[name='ids[]']").prop("checked", true);
  } else {
    $("input[name='ids[]']").prop("checked", false);
  }
});
</script>

app/views/journal_docs/new.html.erb
<header>
  <h3>迁移至 new_admin_journal_doc_path</h3>
</header>
<% if true %>
<%= simple_form_for([@journal, @doc]) do |f| %>
  <%= render partial: "form", locals: { f: f } %>
  <%= f.submit "创建资料", data: { disable_with: "资料创建中……" },
       class: "btn btn-primary" %>
<% end %>
<% end %>

app/views/journal_docs/show.html.erb
<% title(@doc.name) %>
<div id="doc">
  <header>
    <h4><%= link_to @doc.journal.try(:name), @doc.journal %>
      <i class="fa fa-caret-right" aria-hidden="true"></i></h4>
      <h3><%= @doc.name %></h3>
    <ul class="actions">
      <% if policy(@doc).update? %>
      <li>
        <%= link_to t("edit") + t("blank") + t("doc"),
          edit_admin_journal_doc_path(@journal, @doc), class: "edit" %>
      </li>
      <% end %>
      <% if policy(@doc).destroy? %>
      <li>
        <%= link_to t("delete") + t("blank") + t("doc"),
          [@journal, @doc],
          method: :delete,
          data: { confirm: "确定要删除这份资料么？"}, class: "delete" %>
      </li>
      <% end %>
    </ul>
  </header>
  <div class="row">
    <table id = 'attributes'>
      <tr>
        <th>
          <%= t("doc") + t("blank") + t("num") %>：
        </th>
        <td>
          <%= @doc.id %>
        </td>
      </tr>
      <tr>
        <th>
          <%= t("doc") + t("blank") + t("name") %>：
        </th>
        <td>
          <%= @doc.name %></td>
      </tr>
      <tr>
        <th>
          <%= t("receive") %>：
        </th>
        <td>
          <% if @doc.receive %>
            <%= @doc.receive.strftime("%Y-%m-%d") %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>
          <%= t("doc") + t("blank") + t("origin") %>：
        </th>
        <td>
          <%= @doc.origin %>
        </td>
      </tr>
      <tr>
        <th>
          <%= t("doc") + t("blank") + t("receivecount") %>：
        </th>
        <td>
          <%= @doc.amount %>
        </td>
      </tr>
      <tr>
        <th>
          <%= t("doc") + t("blank") + t("attach") %>：
        </th>
        <td>
          <% if @doc.attachments.any? %>
            <div class="attachments">
              <% @doc.attachments.each do |attachment| %>
              <p>
                <% unless attachment.file.url.nil? %>
                <%= link_to File.basename(attachment.file.url),
                  attachment_path(attachment) %>
                (<%= number_to_human_size(attachment.file.size) %>)
                <% end %>
              </p>
              <% end %>
            </div>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>
          <!-- 材料去向： -->
          <%= t("delivery") %>：
        </th>
        <td>
          <% @doc.departments.each do |dept| %>
            <%= dept.name %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>
            <%= t("privatelevel") %>：
        </th>
        <td>
          <%= t(@doc.level, scope: "doc_.level") %>
        </td>
      </tr>
      <tr>
        <th>
            <%= t("doc") + t("blank") + t("state") %>：
        </th>
        <td>
          <span class='status status-<%= @doc.status %>'>
            <%= t(@doc.status, scope: "doc_.status") %>
          </span>
        </td>
      </tr>
      <% if @doc.tags.any? %>
        <tr id="tags">
          <th>
              <%= t("doc") + t("blank") + t("tag") %>：
          </th>
          <td>
            <%= render @doc.tags, doc: @doc %>
          </td>
        </tr>
      <% end %>
      <tr>
        <th>
          <!-- 录入人员： -->
          <%= t("editor") %>：
        </th>
        <td>
          <% unless @doc.editor.nil? %>
          <%= @doc.editor.username %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>
          <!-- 录入时间： -->
          <%= t("created_at") %>：
        </th>
        <td>
          <%= @doc.created_at.to_s(:ymd) %>
        </td>
      </tr>
      <tr>
        <th>
          <%= t("doc") + t("blank") + t("desc") %>：
        </th>
        <td>
          <%= sanitize @doc.description %></td>
      </tr>
      <tr>
        <th>
          <%= t("doc") + t("blank") + "流转" %>：
        </th>
        <td>


          <% if @doc.amount && @doc.amount > 0 %>
          <% @doc.items.each do |item| %>
          <p>
              <%= item.name %>
              <% if item.owner == '资料处' %>
              <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#approvalModal">
                <%= "借阅" %>
              </button>
              <% else %>
              <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#approvalModal">
                <%= "归还" %>
              </button>
              <% end %>
              </p>


          <% end %>



              <!-- modal -->
              <div class="modal fade" id="approvalModal" tabindex="-1"
                role="dialog" aria-labelledby="approvalModalLabel"
                aria-hidden="true">
                <div class="modal-dialog modal-sm">
                  <div class="modal-content">
                    <div class="modal-header">
                      <strong class="modal-title" id="approvalModalLabel">资料流转</strong>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <%= form_tag lend_doc_item_path(journal_id: @journal.shortname, doc_id: @doc.id), method: :get,
                        class: "form-inline" do %>
                        <%= label_tag 'lend', '借阅人：',
                          class: "control-label" %>
                        <%= text_field_tag :lend, params[:lend],
                          class: "form-control" %>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danget"
                          data-dismiss="modal">取消</button>
                        <%= submit_tag "提交", name: nil,
                         class:"btn btn-success" %>
                      <% end %>
                    </div>
                  </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
              </div><!-- /.modal -->
            </li>
          <% end %>

        </td>
      </tr>
      <tr>
        <td colspan="2">
        <% if @doc.images.present? %>
          <% @doc.images.each do |i| %>
            <%= link_to image_tag(i.url(:small)), i.url %>
          <% end %>
        <% end %>
        </td>
      </tr>

    </table>
  </div>
</div>
<header>
  <h4>Comments</h4>
</header>
<div id="comments">
  <% if @doc.comments.persisted.any? %>
    <%= render @doc.comments.persisted %>
  <% else %>
    <p>
      该文件没有评论
    </p>
  <% end %>
</div>

<% if policy(@comment).create? %>
  <%= render "comments/form", doc: @doc, comment: @comment %>
<% end %>