config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'journals#index'
  root 'static_pages#show', page: 'home'
  get '/faq' => 'pages#faq'
  get '/journals/:journal_id/docs/:doc_id/items/:id' => 'journal_docs#lend', as: :lend_doc_item

  namespace :admin do
    root 'application#index'

    resources :journals, only: %i[index new edit update create destroy] do
      resources :docs, only: %i[new edit update create destroy],
                       controller: 'journal_docs' do
        resources :tags, only: [] do
          member do
            delete :remove
          end
        end
      end

      member do
        post :reorder
      end
    end

    resources :books
    resources :orders do
      member do
        post :cancel
        post :prepare
        post :lend
        post :return
      end
    end

    resources :magazines

    resources :csv_imports
    resources :csv_exports

    resources :docs, only: %i[index new edit update create destroy] do
      collection do
        post :bulk_update
        post :import
      end
    end

    resources :versions do
      post :undo
    end

    resources :users do
      member do
        patch :archive
      end
    end

    resources :states, only: %i[index new create] do
      member do
        get :make_default
      end
    end

    resources :departments
  end
  # --- end of admin routes

  resources :journals, only: %i[index show] do
    resources :docs, controller: 'journal_docs' do
      resources :comments, only: [:create]

      resources :tags, only: [] do
        member do
          delete :remove
        end
      end
    end
  end

  resources :docs, only: %i[index show] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  # resources :books, only: %i[index show]
  resources :books do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :orders

  resources :cart_items

  resources :magazines, only: %i[index show]

  resources :attachments, only: %i[show new]

  namespace :account do
    resources :orders
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :books, through: :cart_items, source: :book

  def add_book_to_cart(book)
    ci = cart_items.build
    ci.book = book
    ci.quantity = 1
    ci.save
  end

  def clean!
    cart_items.destroy_all
  end

  def total
    sum = 0
    cart_items.each do |cart_item|
      sum += cart_item.quantity if cart_item.book.present?
    end
    sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_after_action :verify_authorized, :verify_policy_scoped

  def clean
    current_cart.clean!
    flash[:warning] = '已清空借书单'
    redirect_to carts_path
  end

  def checkout
    @order = Order.new
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total(cart)
    cart.total
  end
end

app/views/carts/checkout.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>借阅明细</h2>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">图书明细</th>
          <th>数量</th>
        </tr>
      </thead>
      <tbody>
        <% current_cart.cart_items.each do |cart_item| %>
          <tr>
            <td>
              <%= link_to(cart_item.book.title, book_path(cart_item.book)) %>
            </td>
            <td>
              <%= cart_item.quantity %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <hr/>
  <h2>借阅说明</h2>
  <div class="order-form">
    <%= simple_form_for @order do |f| %>
    <div class="form-group col-lg-12">
      <%= f.input :borrower, label: "借阅人" %>
      <%= f.input :borrow_at, label: "借阅时间", as: :string, input_html: { data: { behaviour: "datepicker" }} %>
      <%= f.input :due_at, label: "归还时间", as: :string, input_html: { data: { behaviur: "datepicker"}} %>
    </div>
    <div class="checkout">
      <%= f.submit "申请借阅", class: "btn btn-lg btn-danger pull-right", data: { disable_with: "借阅申请发送中……"} %>
    </div>
  <% end %>
</div>
</div>
<script type="text/javascript">
$("#order_borrow_at").datepicker({format: "yyyy-mm-dd", language: "<%= I18n.locale %>"});
$("#order_due_at").datepicker({format: "yyyy-mm-dd", language: "<%= I18n.locale %>"});
</script>

app/views/carts/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to("清空借书单", clean_carts_path, method: :delete, class: "pull-right", style: "text-decoration: underline;", data: { confirm: "你确定要清空借书单吗？"}) %>
    <h2>借书单</h2>
    <table class="table table-bordered">
      <thead>
        <th colspan="2">图书信息</th>
        <th>数量</th>
        <th>操作

        </th>
      </thead>
      <tbody>
        <% current_cart.cart_items.each do |cart_item| %>
          <tr>
            <td>
              <%= link_to book_path(cart_item.book) do %>
              <% if cart_item.book.image.present? %>
                <%= image_tag(cart_item.book.image.thumb.url, class: "thumbnail") %>
              <% else %>
                <%= image_tag("", class: "thumbnail") %>
              <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to(cart_item.book.title, book_path(cart_item.book)) %>
          </td>
          <td>
            <%= form_for cart_item, url: cart_item_path(cart_item.book_id) do |f| %>
            <%= f.select :quantity, 1..cart_item.book.copy %>
            <%= f.submit "更新", data: { disable_with: "更新中……"} %>
          <% end %>
        </td>
        <td>
          <%= link_to cart_item_path(cart_item.book_id), method: :delete do %>
          <i class="fa fa-trash"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
</tbody>
</table>
<br/>
<div class="totol clearfix">
<span class="pull-right">
  总计
  <%= render_cart_total(current_cart) %>
  本
</span>
</div>
<hr/>
<div class="checkout clearfix">
<%= link_to("预约", checkout_carts_path, method: :post, class: "btn btn-lg btn-danger pull-right") %>
</div>
</div>
</div>