config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'journals#index'
  root 'static_pages#show', page: 'home'
  get '/faq' => 'pages#faq'
  get '/journals/:journal_id/docs/:doc_id/items/:id' => 'journal_docs#lend', as: :lend_doc_item

  namespace :admin do
    root 'application#index'

    resources :journals, only: %i[index new edit update create destroy] do
      resources :docs, only: %i[new edit update create destroy],
                       controller: 'journal_docs' do
        resources :tags, only: [] do
          member do
            delete :remove
          end
        end
      end

      member do
        post :reorder
      end
    end

    resources :books
    resources :orders do
      member do
        post :cancel
        post :prepare
        post :lend
        post :return
      end
    end

    resources :magazines

    resources :csv_imports
    resources :csv_exports

    resources :docs, only: %i[index new edit update create destroy] do
      collection do
        post :bulk_update
        post :import
      end
    end

    resources :versions do
      post :undo
    end

    resources :users do
      member do
        patch :archive
      end
    end

    resources :states, only: %i[index new create] do
      member do
        get :make_default
      end
    end

    resources :departments
  end
  # --- end of admin routes

  resources :journals, only: %i[index show] do
    resources :docs, controller: 'journal_docs' do
      resources :comments, only: [:create]

      resources :tags, only: [] do
        member do
          delete :remove
        end
      end
    end
  end

  resources :docs, only: %i[index show] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  # resources :books, only: %i[index show]
  resources :books do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :orders

  resources :cart_items

  resources :magazines, only: %i[index show]

  resources :attachments, only: %i[show new]

  namespace :account do
    resources :orders
  end
end

app/models/doc.rb
#
class Doc < ActiveRecord::Base
  STATUS = %w[available lend].freeze
  LEVEL = %w[open internal sensitive secret classified].freeze

  scope :by_status, ->(s) { where(status: s) }
  scope :by_journal, ->(j) { where(journal_id: j) }

  validates_inclusion_of :status, in: STATUS
  validates_inclusion_of :level, in: LEVEL

  validates :name, presence: true

  before_create :assign_default_state

  # after_create :associate_tags_with_doc
  mount_uploaders :images, DocImageUploader
  serialize :images, JSON

  belongs_to :journal
  belongs_to :editor, class_name: 'User', optional: true
  belongs_to :state, optional: true

  has_many :attachments, dependent: :destroy
  accepts_nested_attributes_for :attachments, allow_destroy: true,
                                              reject_if: :all_blank

  has_many :comments, dependent: :destroy
  # has_many :csv_imports, dependent: :destroy
  has_many :docDeliveries
  has_many :departments, through: :docDeliveries
  has_many :items

  has_and_belongs_to_many :tags, uniq: true

  has_paper_trail

  # attr_accessor :tag_names
  # attr_reader :tag_names
  # def receive
  #   receive.to_s(:ymd)
  # end

  def tag_names
    if tags.any?
      tag_names = ''
      tags.each do |t|
        tag_names << t.name
        tag_names << ' '
      end
      tag_names.chop
    end
  end

  def tag_names=(names)
    @tag_names = names
    names.split.each do |name|
      unless tags.find_by_name(name)
        tags << Tag.find_or_initialize_by(name: name)
      end
    end
  end

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  private

  def assign_default_state
    self.state ||= State.default
  end

  # def associate_tags_with_doc
  #   if tag_names
  #     tag_names.split.each do |name|
  #       puts 'associate_tags_with_doc' + name
  #       tags << Tag.find_or_create_by(name: name) unless tags.include?(name)
  #     end
  #   end
  # end
end

app/controllers/admin/docs_controller.rb
#
require 'csv'
class Admin::DocsController < Admin::ApplicationController
  layout 'admin'

  before_action :set_doc, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :admin_required

  def index
    # @docs = Doc.includes(:journal).order('id DESC')
    #            .page(params[:page]).per(10)
    @q = Doc.includes(:journal).ransack(params[:q])
    @docs = @q.result.order('id DESC').page(params[:page]).per(10)

    if params[:status].present? && Doc::STATUS.include?(params[:status])
      @docs = @docs.by_status(params[:status])
    end

    if params[:journal_id].present? && Journal.find_by_id(params[:journal_id])
      @docs = @docs.by_journal(params[:journal_id])
    end

    @docs = @docs.by_status(params[:statuses]) if Array(params[:statuses]).any?

    if Array(params[:journal_ids]).any?
      @docs = @docs.by_journal(params[:journal_ids])
    end

    if params[:start_on].present?
      @docs = @docs.where('publish >= ?',
                          Date.parse(params[:start_on]).beginning_of_day)
    end

    if params[:end_on].present?
      @docs = @docs.where('publish <= ?',
                          Date.parse(params[:end_on]).end_of_day)
    end

    if params[:doc_id].present?
      # TODO: sub('，', ',') maybe put in front-end
      @docs = @docs.where(id: params[:doc_id].sub('，', ',').split(','))
    end

    respond_to do |format|
      format.html
      # TODO: chinese characters code
      format.csv do
        @docs = @docs.reorder('id ASC')
        csv_string = CSV.generate do |csv|
          csv << %w[资料序号 资料名称 出版时间 到刊时间 资料原号 资料份数
                    录入人员 录入时间
                    资料状态 私密程度 资料描述]
          @docs.each do |d|
            csv << [d.id, d.name, d.publish, d.receive, d.origin, d.amount,
                    d.editor.username, d.created_at.to_s(:ymd),
                    t(d.status, scope: 'doc_.status'),
                    t(d.level, scope: 'doc_.level'), d.description]
          end
        end
        send_data csv_string, filename: "doc-#{Time.now.to_s(:number)}.csv"
      end
      format.xlsx
    end

    @docs_all = Doc.all

    if @docs_all.any?
      # TODO: receive may be null
      dates = (@docs_all.order('receive ASC').first.receive.to_date..Date.today).to_a

      status_colors = { 'available' => '#FF6384', 'lend' => '#36A2EB' }

      @date_stat = {
        labels: dates,
        datasets: Doc::STATUS.map do |s|
          {
            label: I18n.t(s, scope: 'doc_.status'),
            data: dates.map do |d|
              @docs_all.by_status(s).where('receive >= ? AND receive <= ?',
                          d.beginning_of_day, d.end_of_day).count
            end,
            borderColor: status_colors[s]
          }
        end
      }


    end
  end

  def new
    @doc = Doc.new
    authorize @doc, :create?
    @doc.attachments.build
  end

  def show
    authorize @doc, :show?
    # TODO: state_id remove?
    @comment = @doc.comments.build(state_id: @doc.state_id)
  end

  def create
    @doc = Doc.new(doc_params)

    whitelisted_params = doc_params
    whitelisted_params.delete(:tag_names) unless policy(@doc).tag?

    @doc.attributes = whitelisted_params
    @doc.editor = current_user
    authorize @doc, :create?

    @doc.attachments.each do |att|
      att.doc = @doc
    end

    if @doc.save
      flash[:notice] = '新增资料成功'
      redirect_to admin_docs_path
    else
      flash[:alert] = '新增资料未成功12'
      render :new
    end
  end

  def edit
    authorize @doc, :update?
    @doc.attachments.build if @doc.attachments.empty?
  end

  def update
    authorize @doc, :update?
    if @doc.update(doc_params)
      flash[:notice] = '更新资料成功'
      redirect_to admin_docs_path
    else
      flash[:alert] = '更新资料未成功'
      render :edit
    end
  end

  def destroy
    authorize @doc, :destroy?
    @doc.destroy
    flash[:notice] = '资料删除成功'
    redirect_to admin_docs_path
  end

  def bulk_update
    total = 0
    if params[:commit] == I18n.t(:bulk_update)
      Array(params[:ids]).each do |doc_id|
        doc = Doc.find(doc_id)
        doc.status = params[:doc_status]
        total += 1 if doc.save
      end
      flash[:notice] = I18n.t(:bulk_update) + " #{total} 篇"
    elsif params[:commit] == I18n.t(:bulk_delete)
      Array(params[:ids]).each do |doc_id|
        doc = Doc.find(doc_id)
        doc.destroy
        total += 1
      end
      flash[:alert] = I18n.t(:bulk_delete) + " #{total} 篇"
    end

    redirect_to admin_docs_path
  end

  def import
    csv_string = params[:csv_file].read.force_encoding('utf-8')
    success = 0
    failed_records = []

    CSV.parse(csv_string) do |row|
      doc = Doc.new(name: row[0],
                    journal: Journal.find(row[1]),
                    description: row[2],
                    publish: row[3],
                    receive: row[4],
                    amount: row[5],
                    status: row[6],
                    origin: row[7],
                    editor_id: row[8],
                    level: row[9])
      if doc.save
        success += 1
      else
        failed_records << [row, registration]
        Rails.logger.info("#{row} ----> #{doc.errors.full_messages}")
      end

      flash[:notice] = "总共汇入 #{success} 笔，失败 #{failed_records.size} 笔"
      redirect_to admin_docs_path
    end
  end

  private

  def doc_params
    params.require(:doc)
          .permit(:origin, :name, :receive, :publish, :journal_id, :level,
                  :description, :editor, :amount, :tag_names, :status,
                  :remove_images,
                  images: [],
                  department_ids: [],
                  attachments_attributes: %i[id file file_cache
                                             description _destory])
  end

  def set_doc
    @doc = Doc.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = '您所查看的外来资料不存在'
    redirect_to docs_path
  end
end

app/controllers/docs_controller.rb
#
class DocsController < ApplicationController
  before_action :set_journal
  before_action :set_doc, only: %i[show edit update destroy]

  def index
    @docs = Doc.all
  end

  def show
    authorize @doc, :show?
    @comment = @doc.comments.build(state_id: @doc.state_id)
  end

  def new
    @doc = @journal.docs.build
    authorize @doc, :create?
    @doc.departments = @journal.departments
    # 3.times { @doc.attachments.build }
    @doc.attachments.build
  end

  def create
    @doc = @journal.docs.new

    whitelisted_params = doc_params
    whitelisted_params.delete(:tag_names) unless policy(@doc).tag?

    @doc.attributes = whitelisted_params
    @doc.editor = current_user
    authorize @doc, :create?

    @doc.attachments.each do |att|
      att.doc = @doc
    end

    if @doc.save
      flash[:notice] = '新增资料成功'
      redirect_to [@journal, @doc]
    else
      flash[:alert] = '新增资料未成功'
      render :new
    end
  end

  def edit
    authorize @doc, :update?
  end

  def update
    authorize @doc, :update?
    if @doc.update(doc_params)
      flash[:notice] = '更新资料成功'
      redirect_to [@journal, @doc]
    else
      flash[:alert] = '更新资料未成功'
      render :edit
    end
  end

  def destroy
    authorize @doc, :destroy?
    @doc.destroy
    flash[:notice] = '资料删除成功'
    redirect_to @journal
  end

  private

  def doc_params
    params.require(:doc)
          .permit(:origin, :name, :receive, :publish, :journal_id, :level,
                  :description, :editor, :amount, :tag_names, :status,
                  attachments_attributes: %i[file file_cache],
                  department_ids: [])
  end

  def set_doc
    @doc = @journal.docs.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = '您所查看的外来资料不存在'
    redirect_to docs_path
  end

  def set_journal
    # puts params[:journal_id]
    @journal = Journal.find_by_shortname!(params[:journal_id])
  end
end

app/helpers/admin/docs_helper.rb
module Admin::DocsHelper
  def doc_filters(options)
    params.permit(:status, :journal_id).merge(options)
  end
end

app/helpers/docs_helper.rb
module DocsHelper
  def state_transition_for(comment)
    #   if comment.previous_state != comment.state
    #     content_tag(:p) do
    #       value = "<strong><i class='fa fa-gear'></i> 状态改变</strong>"
    #       if comment.previous_state.present?
    #         value += " 从 #{render comment.previous_state}"
    #       end
    #       value += " 为 #{render comment.state}"
    #       value.html_safe
    #     end
    #   end
  end
end

app/views/admin/docs/_form.html.erb
<%= f.association :journal, label: '刊物名称' %>
<%= f.input :name, label: "资料标题" %>
<%= f.input :origin, label: "原始编号" %>
<%= f.input :level, label: "私密程度", as: :select, prompt: "请选择私密程度",
  collection: Doc::LEVEL.map { |s| [t(s, :scope=>"doc_.level"), s] } %>
<%= f.input :status, label: "资料状态", as: :radio_buttons,
  collection: Doc::STATUS.map { |s| [t(s, :scope=>"doc_.status"), s] },
  class: "btn-group" %>
<%= f.input :receive, as: :string, label: "到刊时间",
  input_html: { data: { behaviour: "datepicker" }}  %>
<%= f.input :publish, as: :string, label: "出版时间",
  input_html: { data: { behaviour: "datepicker" }}  %>
<%= f.input :description, as: :text, label: "资料描述" %>
<%= render "tags/form", f: f %>
<%= f.input :amount, label: "资料份数" %>
<%= f.association :departments, as: :check_boxes, label: "资料分发" %>
<div class="form-group">
  <label>资料图片</label>
  <%= f.file_field :images, multiple: true, class: "form-control" %>
  <% if f.object.images.present? %>
    <label>
      <%= f.check_box :remove_images %>删除图档
    </label>
    <% f.object.images.each do |i| %>
      <%= link_to i.filename, i.url, target: "_blank" %>
    <% end %>
  <% end %>
</div>


<div id="attachments">
  <%= render partial: "attachments/form", locals: { f: f, index: 0 } %>
</div>
<p>
  <%= link_to "新增附件", new_attachment_path, remote: true, id: "add_file",
    data: { params: { index: @doc.attachments.size } } %>
</p>


<%= f.nested_fields_for :attachments do |ff| %>
  <fieldset style="border-left: 5px solid #bbb;
                   margin-bottom: 10px; padding: 10px;">
    <legend>
      资料附件
    </legend>
    <div class="form-group">
      <%= ff.label :file %>
      <%= ff.file_field :file, class: "form-control" %>
      <% if ff.object.file.present? %>
        已上传附件 <%= link_to ff.object.description, ff.object.file.url,
         target: "_blank" %>
      <% end %>
    </div>
    <div class="form-group">
      <%= ff.label :description %>
      <%= ff.text_field :description, class: "form-control"%>
    </div>
    <%= ff.remove_nested_fields_link "移除", class: "btn btn-danger" %>
  </fieldset>
<% end %>
<p class="text-right">
   <%= f.add_nested_fields_link :attachments, "新增档案", class: "btn btn-default" %>
</p>

<script>
  $("#doc_journal_id").select2( {theme: "bootstrap"} );
  $("#doc_receive").datepicker({ format: "yyyy-mm-dd",
    language: "<%= I18n.locale %>" });
  $("#doc_publish").datepicker({ format: "yyyy-mm-dd",
    language: "<%= I18n.locale %>" });
</script>

app/views/admin/docs/edit.html.erb
<header>
  <h3>编辑资料</h3>
</header>
<%= simple_form_for [:admin, @doc] do |f| %>
  <%= render partial: "form", locals: { f: f } %>
  <%= f.submit t("update") + t("blank") + t("doc"),
    data: { disable_with: "资料更新中……" },
    class: "btn btn-primary" %>
<% end %>

app/views/admin/docs/index.html.erb
<header>
<h3><%= t("doc_list") %></h3>
<% admins_only do %>
<ul class="actions" style="padding-bottom: 5px;">
  <li>
    <%= link_to(t("create") + t("blank") + t("doc"),
    new_admin_doc_path, class: "new") %>
  </li>
  <li>
    <%= link_to("导入" + t("blank") + t("doc"), admin_csv_imports_path,
     class: "btn btn-primary") %>
  </li>
</ul>
<% end %>
</header>
<% if false %>
<div class="submenu">
  <div class="btn-group">
    <%= link_to "#{t('all')} (#{Doc.count})",
          admin_docs_path(doc_filters(status: nil)),
          class: "btn btn-success btn-group
                  #{(params[:status].blank?) ? "active" : "" }" %>
    <% Doc::STATUS.each do |s| %>
      <%= link_to t(s, scope: 'doc_.status') + " (#{Doc.by_status(s).count})",
          admin_docs_path(doc_filters(status: s)),
          class: "btn btn-success btn-group
                  #{(params[:status] == s) ? "active" : "" }" %>
    <% end %>
  </div>
  <div class="btn-group">
    <%= link_to "#{t('all')} (#{Doc.count})",
          admin_docs_path(doc_filters(journal_id: nil)),
          class: "btn btn-default btn-group
            #{(params[:journal_id].blank?) ? "active" : "" }" %>
    <% Journal.all.each do |j| %>
      <%= link_to j.name + " (#{Doc.by_journal(j).count})",
      admin_docs_path(doc_filters(journal_id: j.id)),
      class: "btn btn-default btn-group
              #{(params[:journal_id] == j.id.to_s) ? "active" : "" }" %>
    <% end %>
  </div>
</div>
<% end %>
<div class="submenu" width="100%">
<%= search_form_for @q, url: admin_docs_path, method: :get do |f| %>
<table class="table  table-hover">
  <tr>
    <td width="100px">
      资料名称
    </td>
    <td>
      <%= f.search_field :name_cont, placeholder: "资料名称",
       class: "form-control" %>
    </td>
  </tr>
  <tr>
    <td>
      资料描述
    </td>
    <td>
      <%= f.search_field :description_cont, placeholder: "资料描述",
       class: "form-control" %>
    </td>
  </tr>
  <tr>
    <td>
      资料序号
    </td>
    <td>
      <%= text_field_tag :doc_id, params[:doc_id],
        placeholder: "资料序号，可用逗号（ ，）区隔", class: "form-control" %>
    </td>
  </tr>
  <tr>
    <td>
      刊物名称
    </td>
    <td>
      <% Journal.all.each do |j| %>
        <%= check_box_tag "journal_ids[]", j.id,
          Array(params[:journal_ids]).include?(j.id.to_s) %>
        <%= j.name %>
        (<%= Doc.by_journal(j).count %>)
      <% end %>
    </td>
  </tr>
  <tr>
    <td>
      资料状态
    </td>
    <td>
      <% Doc::STATUS.each do |s| %>

          <%= check_box_tag "statuses[]", s,
            Array(params[:statuses]).include?(s) %>
          <%= t(s, scope: "doc_.status")%>
          (<%= Doc.by_status(s).size %>)

      <% end %>
    </td>
  </tr>
  <tr>
    <td>
      资料时间
    </td>
    <td>
      <%= date_field_tag :start_on, params[:start_on] %> ~
      <%= date_field_tag :end_on, params[:end_on] %>
    </td>
  </tr>
  <tr>
    <td class="text-right" colspan="2">
      <%= submit_tag "查询", class: "btn btn-primary" %>
    </td>
  </tr>
</table>
<% end %>
</div>
<div id="docs" class="row">
<%= form_tag bulk_update_admin_docs_path, class: "table" do %>
<table class="table table-bordered">
<thead>
  <tr>
    <th>
      <%= check_box_tag "全选", "1", false, id: "toggle_all" %>
    </th>
    <th>
      <%= t("num") %>
    </th>
    <th>
      <%= t("journal") + t("blank") + t("name") %>
    </th>
    <th>
      <%= t("doc") + t("blank") + t("name") %>
    </th>
    <th>
      <%= t("origin") %>
    </th>
    <!-- <th>
      <%= t("receivecount") %>
    </th> -->
    <th>
      <%= t("receive") %>
    </th>
    <th>
      <%= t("operation") %>
    </th>
  </tr>
</thead>
<tbody>
  <% @docs.each do |doc| %>
  <tr>
    <td>
      <%= check_box_tag "ids[]", doc.id %>
    </td>
    <td>
      <%= link_to(doc.id, doc_path(doc)) %>
    </td>
    <td>
      <%= doc.journal.name %>
    </td>
    <td>
      <%= link_to doc.name, journal_doc_path(doc.journal, doc) %>
    </td>
    <td>
      <%= link_to doc.origin, journal_doc_path(doc.journal, doc) %>
    </td>
    <!-- <td>
      <%= doc.amount %>
    </td> -->
    <td>
      <%= doc.receive %>
    </td>
    <td>
      <%= link_to t("edit"), edit_admin_doc_path(doc), class: "edit" %>
      <%= link_to t("delete"), admin_doc_path(doc),
          method: :delete, data: { confirm: "确定要删除这份资料么？"},
          class: "delete" %>
    </td>
  </tr>
  <% end %>
</tbody>
</table>
<%= paginate @docs %>
<% end %>
</div>

<p>
  <%= select_tag :doc_status,
    options_for_select([[t("available", scope: "doc_.status"), "available"],
                        [t("lend", scope: "doc_.status"), "lend"]]),
    class: "form-control", style: "width: 80px; display: inline"%>
  <%= submit_tag t(:bulk_update), class: "btn btn-primary" %>
  <%= submit_tag t(:bulk_delete), class: "btn btn-danger",
    data: { confirm: "你确定要批量删除么？" } %>
  <%= link_to "导出 CSV", admin_docs_path(format: :csv),
    class: "btn btn-default" %>
  <%= link_to "导出 Excel", admin_docs_path(format: :xlsx),
    class: "btn btn-default" %>


<hr />
<canvas id="chartDate" width="400" height="200"></canvas>
<hr  />
<%= form_tag import_admin_docs_path(), multipart: true, class: "inline" do %>
  <p>
    <%= file_field_tag "csv_file" %>
  </p>
  <p>
    <%= submit_tag "汇入CSV", class: "btn btn-danger" %>
  </p>
<% end %>
</p>

<script>
  var ctxDate = document.getElementById("chartDate");
  var dateChart = new Chart(ctxDate, {
    type: 'line',
    data: <%= raw @date_stat.to_json %>,
    option: {
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero:true
          }
        }]
      }
    }
  });
</script>

<script>
$("#toggle_all").click(function(){
  if ( $(this).prop("checked") ) {
    $("input[name='ids[]']").prop("checked", true);
  } else {
    $("input[name='ids[]']").prop("checked", false);
  }
});
</script>

app/views/admin/docs/new.html.erb
<header>
  <h3>新增资料</h3>
</header>
<%= simple_form_for [:admin, @doc] do |f| %>
  <%= render partial: "form", locals: { f: f } %>
  <%= f.submit "创建资料", data: { disable_with: "资料创建中……" },
    class: "btn btn-primary" %>
<% end %>

app/views/admin/docs/show.html.erb
<% title(@doc.name) %>
<div id="doc">
  <header>
      <h4><%= link_to @doc.journal.try(:name), @doc.journal %>
      <i class="fa fa-caret-right" aria-hidden="true"></i></h4>
      <h3><%= @doc.name %></h3>
    <ul class="actions">
      <% if policy(@doc).update? %>
      <li>
        <%= link_to t("edit") + t("blank") + t("doc"),
          edit_admin_doc_path(@doc), class: "edit" %>
      </li>
      <% end %>
      <% if policy(@doc).destroy? %>
      <li>
        <%= link_to t("delete") + t("blank") + t("doc"),
          admin_docs_path,
          method: :delete,
          data: { confirm: "确定要删除这份资料么？"}, class: "delete" %>
      </li>
      <% end %>
    </ul>
  </header>
  <div class="row">
    <p>
      <%= t("doc") + t("blank") + t("num") %>：<%= @doc.id %>
    </p>
    <p>
      <%= t("doc") + t("blank") + t("name") %>：<%= @doc.name %></td>
    </p>
    <p>
      <%= t("publish") %>：<%= @doc.publish %>
    </p>
    <p>
      <%= t("receive") %>：<%= @doc.receive %>
    </p>
    <p>
      <%= t("doc") + t("blank") + t("origin") %>：<%= @doc.origin %>
    </p>
    <p>
      <%= t("doc") + t("blank") + t("receivecount") %>：<%= @doc.amount %>
    </p>

    <p>
      <%= t("doc") + t("blank") + t("attach") %>：
      <% if @doc.attachments.any? %>
        <div class="attachments">
          <% @doc.attachments.each do |attachment| %>
          <p>
            <% unless attachment.file.url.nil? %>
            <%= link_to File.basename(attachment.file.url),
              attachment_path(attachment) %>
            (<%= number_to_human_size(attachment.file.size) %>)
            <% end %>
          </p>
          <% end %>
        </div>
      <% end %>
    </p>
    <!-- 材料去向： -->
    <p>
      <%= t("delivery") %>：
      <% @doc.departments.each do |dept| %>
        <%= dept.name %>
      <% end %>
    </p>
    <!-- 录入人员： -->
    <p>
      <%= t("editor") %>：
      <% unless @doc.editor.nil? %>
        <%= @doc.editor.username %>
      <% end %>
    </p>
    <!-- 录入时间： -->
    <p>
      <%= t("created_at") %>：<%= @doc.created_at.to_s(:ymd) %>
    </p>
    <p>
      <%= t("doc") + t("blank") + t("state") %>：
        <%= t(@doc.status, scope: "doc_.status") %>
    </p>
    <p>
      <%= t("privatelevel") %>：<%= t(@doc.level, scope: "doc_.level") %>
    </p>
    <% if @doc.tags.any? %>
    <p>
      <%= t("doc") + t("blank") + t("tag") %>：
        <% @doc.tags.each do |t| %>
          <%= t.name %>
        <% end %>
    </p>
    <% end %>
    <p>
      <%= t("doc") + t("blank") + t("desc") %>：
      <%= sanitize @doc.description %>
    </p>
    <p>
      <% if @doc.images.present? %>
        <% @doc.images.each do |i| %>
          <%= link_to image_tag(i.url(:small)), i.url %>
        <% end %>
      <% end %>
    </p>
  </div>
</div>

<header>
  <h4>Comments</h4>
</header>
<div id="comments">
  <% if @doc.comments.persisted.any? %>
    <%= render @doc.comments.persisted %>
  <% else %>
    <p>
      该文件没有评论
    </p>
  <% end %>
</div>

<% if policy(@comment).create? %>
  <%= render "comments/form", doc: @doc, comment: @comment %>
<% end %>